---
title: "Practice Heat Shocks"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
  word_document:
    toc: yes
---

# Libraries
```{r}
library(lubridate)
library(dplyr)
library(ggplot2)
library(tidyr)
library(data.table)
```

```{r}
dat<-fread("https://raw.githubusercontent.com/HannahHChu/Proteome_stability_project/master/Data/2018-06-21_thermal_assays_masterdatasheet.csv")

#glimpse(dat)
```


# Changing MIN:SEC to minutes
```{r}
rtime<- dat$kd_time
time<-lubridate::minute(ms(rtime))+lubridate::second(ms(rtime))/60
#time

#Adding new column of correct time
dat$time<-time
```

# Creating the Data Frame
```{r}
df<-data.frame(dat$kd_temp, dat$time, dat$treatment, dat$line)

#filtering out the non-static practice trials
staths<- df%>%
          filter(dat$treatment == "static")
```

# Figures
```{r}
#Overview of static HS 
staticoverview <- ggplot(staths,aes(x=dat.kd_temp,y=dat.time))+geom_point()+
  labs(x = "KD Temperature (ºC)", y = "KD time (min)") + theme(
        axis.ticks.x=element_blank(),legend.position="bottom",
        axis.ticks.y=element_blank(),panel.background = element_blank(),
        panel.grid.major = element_blank(),panel.grid.minor =
          element_blank(),axis.text=element_text(size=9),text=element_text(size=15))+geom_smooth(method="auto", se=F)
staticoverview 

#Static HS based on line
p<- ggplot(staths,aes(x=dat.kd_temp,y=dat.time, colour=dat.line))+geom_point()+
  labs(x = "KD Temperature (ºC)", y = "KD time (min)") + theme(
        axis.ticks.x=element_blank(),legend.position="bottom",
        axis.ticks.y=element_blank(),panel.background = element_blank(),
        panel.grid.major = element_blank(),panel.grid.minor =
          element_blank(),axis.text=element_text(size=9),text=element_text(size=15))+geom_smooth(method="auto", se=F)
fig <- p + scale_colour_discrete(name = "lines")
fig

#Overview of slow ramp
slowdat <- df%>%
  filter(dat$treatment == "slow", dat$kd_temp > "37")

slowoverview <- ggplot(slowdat,aes(x=dat.kd_temp,y=dat.time))+geom_point()+
  labs(x = "KD Temperature (ºC)", y = "KD time (min)") + theme(
        axis.ticks.x=element_blank(),legend.position="bottom",
        axis.ticks.y=element_blank(),panel.background = element_blank(),
        panel.grid.major = element_blank(),panel.grid.minor =
          element_blank(),axis.text=element_text(size=9),text=element_text(size=15))+geom_smooth(method="auto", se=F)
slowoverview

#Slow ramp HS based on line
q<- ggplot(slowdat,aes(x=dat.kd_temp,y=dat.time, colour=dat.line))+geom_point()+
  labs(x = "KD Temperature (ºC)", y = "KD time (min)") + theme(
        axis.ticks.x=element_blank(),legend.position="bottom",
        axis.ticks.y=element_blank(),panel.background = element_blank(),
        panel.grid.major = element_blank(),panel.grid.minor =
          element_blank(),axis.text=element_text(size=9),text=element_text(size=15))+geom_smooth(method="auto", se=F)
slowfig <- q + scale_colour_discrete(name = "lines")
slowfig

#Overview of fast ramp
fastdat <- df%>%
  filter(dat$treatment == "fast")

fastoverview <- ggplot(fastdat,aes(x=dat.kd_temp,y=dat.time))+geom_point()+
  labs(x = "KD Temperature (ºC)", y = "KD time (min)") + theme(
        axis.ticks.x=element_blank(),legend.position="bottom",
        axis.ticks.y=element_blank(),panel.background = element_blank(),
        panel.grid.major = element_blank(),panel.grid.minor =
          element_blank(),axis.text=element_text(size=9),text=element_text(size=15))+geom_smooth(method="auto", se=F)
fastoverview

#Fast ramp HS based on line
r<- ggplot(fastdat,aes(x=dat.kd_temp,y=dat.time, colour=dat.line))+geom_point()+
  labs(x = "KD Temperature (ºC)", y = "KD time (min)") + theme(
        axis.ticks.x=element_blank(),legend.position="bottom",
        axis.ticks.y=element_blank(),panel.background = element_blank(),
        panel.grid.major = element_blank(),panel.grid.minor =
          element_blank(),axis.text=element_text(size=9),text=element_text(size=15))+geom_smooth(method="auto", se=F)
fastfig <- r + scale_colour_discrete(name = "lines")
fastfig
```

# Session Info
```{r}
sessionInfo()
```